/**
 * Walks apps/web/dist and produces a typed manifest of base64-encoded bytes
 * that can be embedded inside the compiled binary by `bun build --compile`.
 *
 * Modes:
 *   --mode=release      (default in CI) — fails with DashboardNotBuiltError if dist is missing.
 *   --mode=dev          — writes an empty manifest and logs a warning.
 *   --mode=package-local — like dev, for local package builds without apps/web present.
 *
 * Public API (exported for testing):
 *   - loadAssets(distPath) — collects file entries from a directory tree
 *   - renderManifestSource(assets) — renders the TypeScript source string
 *   - generateManifest(options) — top-level orchestrator
 *   - DashboardNotBuiltError — thrown in release mode when dist is missing
 *
 * Bun-native: no node:fs or node:path imports. Uses Bun.file, Bun.write, Bun.Glob,
 * and import.meta.dir for all I/O and path manipulation. `@types/node` is intentionally
 * NOT a dependency of this workspace.
 */

const DEFAULT_WEB_DIST = `${import.meta.dir}/../../../apps/web/dist`;
const DEFAULT_OUTPUT = `${import.meta.dir}/../src/manifest.generated.ts`;
// A built dashboard always produces index.html; we use its presence as the
// "dist exists and has been built" marker. This avoids the need for a
// dir-vs-file distinction that the Bun file API does not expose.
const BUILD_MARKER = 'index.html';

export type GenerateMode = 'release' | 'dev' | 'package-local';

export interface GenerateOptions {
  readonly mode: GenerateMode;
  readonly distPath: string;
  readonly outputPath: string;
}

export interface AssetEntry {
  readonly relPath: string;
  readonly contentType: string;
  readonly b64: string;
}

export class DashboardNotBuiltError extends Error {
  override readonly name = 'DashboardNotBuiltError';
  constructor(distPath: string) {
    super(`Dashboard assets not found at "${distPath}" — run "bun run build" in apps/web first.`);
  }
}

/**
 * Collects all files under distPath as base64-encoded entries, sorted by
 * relative path for deterministic output.
 *
 * Example:
 *   const assets = await loadAssets('/tmp/dist');
 *   // → [{ relPath: 'index.html', contentType: 'text/html;charset=utf-8', b64: '...' }]
 */
export async function loadAssets(distPath: string): Promise<readonly AssetEntry[]> {
  const entries: AssetEntry[] = [];
  const glob = new Bun.Glob('**/*');
  for await (const relPath of glob.scan({ cwd: distPath, onlyFiles: true })) {
    const normalized = relPath.split('\\').join('/');
    const file = Bun.file(`${distPath}/${normalized}`);
    const bytes = await file.bytes();
    entries.push({
      relPath: normalized,
      contentType: file.type,
      b64: Buffer.from(bytes).toString('base64'),
    });
  }
  return entries.sort((a, b) => a.relPath.localeCompare(b.relPath));
}

const MANIFEST_HEADER =
  `/* eslint-disable */\n` +
  `// This file is generated by packages/web-assets/scripts/generate.ts.\n` +
  `// Do not edit by hand.\n\n` +
  `export interface WebAsset {\n` +
  `  readonly path: string;\n` +
  `  readonly contentType: string;\n` +
  `  readonly bytes: Uint8Array;\n` +
  `}\n\n` +
  `function decode(b64: string): Uint8Array {\n` +
  `  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));\n` +
  `}\n\n`;

/** Renders the TypeScript manifest source from a list of asset entries. Pure function — no I/O. */
export function renderManifestSource(assets: readonly AssetEntry[]): string {
  if (assets.length === 0) {
    return `${MANIFEST_HEADER}export const ASSETS: ReadonlyMap<string, WebAsset> = new Map();\n`;
  }
  const entries = assets.map(
    ({ relPath, contentType, b64 }) =>
      `  [${JSON.stringify(relPath)}, { path: ${JSON.stringify(relPath)}, contentType: ${JSON.stringify(contentType)}, bytes: decode(${JSON.stringify(b64)}) }],`,
  );
  return `${MANIFEST_HEADER}export const ASSETS: ReadonlyMap<string, WebAsset> = new Map([\n${entries.join('\n')}\n]);\n`;
}

export async function generateManifest(options: GenerateOptions): Promise<void> {
  const { mode, distPath, outputPath } = options;

  const distBuilt = await Bun.file(`${distPath}/${BUILD_MARKER}`).exists();

  if (!distBuilt) {
    if (mode === 'release') {
      throw new DashboardNotBuiltError(distPath);
    }
    await Bun.write(outputPath, renderManifestSource([]));
    process.stderr.write(
      `[web-assets] WARNING: dist not found at "${distPath}"; wrote empty manifest. Run "bun run build" in apps/web.\n`,
    );
    return;
  }

  const assets = await loadAssets(distPath);
  await Bun.write(outputPath, renderManifestSource(assets));

  const rawBytes = assets.reduce((sum, a) => sum + Math.ceil((a.b64.length * 3) / 4), 0);
  process.stderr.write(
    `[web-assets] wrote ${outputPath} (${assets.length} files, ${rawBytes} bytes)\n`,
  );
}

function parseMode(argv: readonly string[]): GenerateMode {
  for (const arg of argv) {
    if (arg === '--mode=release') return 'release';
    if (arg === '--mode=dev') return 'dev';
    if (arg === '--mode=package-local') return 'package-local';
  }
  return 'dev';
}

if (import.meta.main) {
  const mode = parseMode(process.argv);
  await generateManifest({ mode, distPath: DEFAULT_WEB_DIST, outputPath: DEFAULT_OUTPUT });
}
